services:
  backend:
    build:
      context: ./backend
    container_name: stockvisor-backend
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=development
    networks:
      - stockvisor-network

  frontend:
    build:
      context: ./frontend
    container_name: stockvisor-frontend
    ports:
      - "3000:3000"
    networks:
      - stockvisor-network
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules

networks:
  stockvisor-network:
    driver: bridge
